INSERT INTO FITNES_CENTAR(ADRESA, EMAIL, NAZIV, TELEFON) VALUES('Patrijaha Pavla 10', 'extremegym@gmail.com', 'Extreme gym', '021325125');

INSERT INTO SALA (KAPACITET, OZNAKA, FITNES_CENTAR_ID) VALUES ('100', 'G1', 1);
INSERT INTO SALA (KAPACITET, OZNAKA, FITNES_CENTAR_ID) VALUES ('35', 'G2', 1);
INSERT INTO SALA (KAPACITET, OZNAKA, FITNES_CENTAR_ID) VALUES ('20', 'F1', 1);
INSERT INTO SALA (KAPACITET, OZNAKA, FITNES_CENTAR_ID) VALUES ('20', 'F2', 1);

INSERT INTO KORISNIK (KORISNICKO_IME, LOZINKA, IME, PREZIME, TELEFON, EMAIL, DATUM_RODJENJA, ULOGA, AKTIVAN, FITNES_CENTAR_ID) VALUES ('radojicic.bojan', '060000', 'Bojan', 'Radojicic', '06499394959', 'bojanradoijcic00@gmail.com', NULL, 'ADMINISTATOR', '1', 1);
INSERT INTO KORISNIK (KORISNICKO_IME, LOZINKA, IME, PREZIME, TELEFON, EMAIL, DATUM_RODJENJA, ULOGA, AKTIVAN, FITNES_CENTAR_ID) VALUES ('mirkovic.bojan', '12422', 'Bojan', 'Mirkovic', '0626443431', 'mirkovicbojan@gmail.com', NULL, 'TRENER', '1', 1);
INSERT INTO KORISNIK (KORISNICKO_IME, LOZINKA, IME, PREZIME, TELEFON, EMAIL, DATUM_RODJENJA, ULOGA, AKTIVAN, FITNES_CENTAR_ID) VALUES ('jovanovic.ivana', '45254', 'Ivana', 'Jovanovic', '0605405454', 'ivana44@gmail.com', NULL, 'TRENER', '1', 1);
INSERT INTO KORISNIK (KORISNICKO_IME, LOZINKA, IME, PREZIME, TELEFON, EMAIL, DATUM_RODJENJA, ULOGA, AKTIVAN, FITNES_CENTAR_ID) VALUES ('markovic.marta', '42542ft', 'Marta', 'Markovic', '0643434534', 'marta06@gmail.com', NULL, 'TRENER', '1', 1);
INSERT INTO KORISNIK (KORISNICKO_IME, LOZINKA, IME, PREZIME, TELEFON, EMAIL, DATUM_RODJENJA, ULOGA, AKTIVAN, FITNES_CENTAR_ID) VALUES ('jovanovic.davor', 'sada44', 'Davor', 'Jovanovic', '0643764374', 'jovanovicdaki@gmail.com', NULL, 'CLAN', '1', 1);
INSERT INTO KORISNIK (KORISNICKO_IME, LOZINKA, IME, PREZIME, TELEFON, EMAIL, DATUM_RODJENJA, ULOGA, AKTIVAN, FITNES_CENTAR_ID) VALUES ('mira11', '12345', 'Mira', 'Kolakovic', '0647889995', 'kolakmira@gmail.com', NULL, 'CLAN', '1', 1);
INSERT INTO KORISNIK (KORISNICKO_IME, LOZINKA, IME, PREZIME, TELEFON, EMAIL, DATUM_RODJENJA, ULOGA, AKTIVAN, FITNES_CENTAR_ID) VALUES ('ostoja00', 'bosna1', 'Ostoja', 'Ostojic', '06322233344', 'samoostoja@gmail.com', NULL, 'CLAN', '1', 1);
INSERT INTO KORISNIK (KORISNICKO_IME, LOZINKA, IME, PREZIME, TELEFON, EMAIL, DATUM_RODJENJA, ULOGA, AKTIVAN, FITNES_CENTAR_ID) VALUES ('mitar064', 'mitrogol', 'Igor', 'Mitrovic', '0645031734', 'mitrogol@gmail.com', NULL, 'CLAN', '1', 1);
INSERT INTO KORISNIK (KORISNICKO_IME, LOZINKA, IME, PREZIME, TELEFON, EMAIL, DATUM_RODJENJA, ULOGA, AKTIVAN, FITNES_CENTAR_ID) VALUES ('oreol', 'oreol1', 'Milica', 'Kupus', '064256317', 'kupus@gmail.com', NULL, 'CLAN', '1', 1);

INSERT INTO TRENING(OPIS, TRAJANJE, NAZIV, TIP_TRENINGA, TRENER_ID) VALUES ('Rast misica', 60, 'Teretana za muskarce', 'Teretana', 2);
INSERT INTO TRENING(OPIS, TRAJANJE, NAZIV, TIP_TRENINGA, TRENER_ID) VALUES ('Rast misica', 55, 'Teretana za zene', 'Teretana', 2);
INSERT INTO TRENING(OPIS, TRAJANJE, NAZIV, TIP_TRENINGA, TRENER_ID) VALUES ('Kardio trening izdrzljivosti', 90, 'Kardio trening', 'Kardio', 3);
INSERT INTO TRENING(OPIS, TRAJANJE, NAZIV, TIP_TRENINGA, TRENER_ID) VALUES ('Treniranje kroz ples', 45, 'Zabava', 'Zabavni trening', 4);

INSERT INTO TERMIN(CENA, VREME_POCETKA, SALA_ID, TRENING_ID) VALUES (250, NULL, 1, 1);
INSERT INTO TERMIN(CENA, VREME_POCETKA, SALA_ID, TRENING_ID) VALUES (200, NULL, 2, 1);
INSERT INTO TERMIN(CENA, VREME_POCETKA, SALA_ID, TRENING_ID) VALUES (200, NULL, 3, 2);

INSERT INTO PRIJAVA(OCENA, CLAN_ID, TERMIN_ID) VALUES (10, 5, 1);
INSERT INTO PRIJAVA(OCENA, CLAN_ID, TERMIN_ID) VALUES (8, 5, 2);
INSERT INTO PRIJAVA(OCENA, CLAN_ID, TERMIN_ID) VALUES (6, 6, 3);

